### ISSUE TITLE
MS Learn Module Update Request: [REPLACE_WITH_MODULE_TITLE]

### ISSUE THREAD

**Issue by MuskanFalwaria** [githubpartners/microsoft-learn#100]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

Build and deploy applications to Azure by using GitHub Actions

### Additional information

- [X] Fix a broken user experience (broken links, exercise error, etc.)
- [ ] Update incorrect information
- [ ] Add new content to the module
- [ ] Some other request

**Comment by Chukslord1** [comment]
Hi @MuskanFalwaria ,

Thank you so much for submitting this issue and we apologize for your inconvenient experience.

Unfortunately, since we don’t have sufficient information to track down the specific concern, we are going to close out this issue.

You can re-open the issue if you provide the specific module that needs to be updated and the specific issue you found (eg. broken link, incorrect information, etc…)
