### ISSUE TITLE
MS Learn Module Update Request: [REPLACE_WITH_MODULE_TITLE]

### ISSUE THREAD

**Issue by McCheco** [githubpartners/microsoft-learn#109]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

Introduction to GitHub

### Additional information

- [ ] Fix a broken user experience (broken links, exercise error, etc.)
- [ ] Update incorrect information
- [X] Add new content to the module
- [ ] Some other request

**Comment by Chukslord1** [comment]
Hi @McCheco ,

Thank you so much for submitting this issue and we apologize for your inconvenient experience.

Unfortunately, since we don’t have sufficient information to track down the specific concern, we are going to close out this issue.

You can reopen the issue if you specify the area that requires additional content to be added.
