### ISSUE TITLE
Could not view .../open completion panel

### ISSUE THREAD

**Issue by kbs-code** [githubpartners/microsoft-learn#111]
The following instructions could not followed from the course:
```
Stop typing and view the Copilot suggestion by hovering over the red squiggly and select the ...
Click Open Completions Panel. Copilot will synthesize around 10 different code suggestions. You should see something like this: Screen Shot 2023-04-27 at 10 06 55 AM
```
The Github landing page would not result after completing the last step.

**Comment by Chukslord1** [comment]
Hi @kbs-code ,

Thank you so much for submitting this issue and we apologize for your inconvenient experience.

Unfortunately, since we don’t have sufficient information to track down the specific concern, we are going to close out this issue.

You can re-open the issue if you provide the specific module that needs to be updated.
