### ISSUE TITLE
Instruction module on vision studio code and github 

### ISSUE THREAD

**Issue by rjurgena** [githubpartners/microsoft-learn#95]
This probably is new but I had to submit it to get it off my chest.  The instructions module set us off to get the github copilot before it showed us how to open the Vision Studio Code.  After opening the Vision Studio Code application, the instructions sent us out from within the VS Code application.  The resulting confusion would probably not have been a problem for someone more familiar with the ops but, it cost me a couple of hours to figure it out.

**Comment by Chukslord1** [comment]
Hi @rjurgena ,

Thank you so much for submitting this issue and we apologize for your inconvenient experience.

Unfortunately, since we don’t have sufficient information to track down the specific concern, we are going to close out this issue.

You can re-open the issue if you provide the specific module that needs to be updated.
