### ISSUE TITLE
MS Learn Module Update Request: [REPLACE_WITH_MODULE_TITLE]

### ISSUE THREAD

**Issue by vedan28** [githubpartners/microsoft-learn#96]
### Which of the MS Learn modules from the dropdown are you submitting an update request?

None

### Additional information

- [X] Fix a broken user experience (broken links, exercise error, etc.)
- [ ] Update incorrect information
- [ ] Add new content to the module
- [ ] Some other request

### Information about the requested update

Improve broken user experience

**Comment by Chukslord1** [comment]
Hi @vedan28 ,

Thank you so much for submitting this issue and we apologize for your inconvenient experience.

Unfortunately, since we don’t have sufficient information to track down the specific concern, we are going to close out this issue.

You can re-open the issue if you provide the specific module that needs to be updated.
